### PR TITLE
Release gtoken v2.3.2

### PR DESCRIPTION
**Pull request by stephenplusplus**
This pull request was generated using releasetool.

### CODE REVIEW

**Comment by stephenplusplus** [comment]
Linked and tested, and it seems to be working!

**Comment by stephenplusplus** [comment]
@justinbeckwith how do we get this on npm? :)

**Comment by stephenplusplus** [comment]
So I know for next time, what was the process? Did something go wrong behind the scenes?

**Comment by JustinBeckwith** [comment]
So 2 things:
1. Kokoro jobs were having trouble catching up, but that's good now
2. You need to update your version of `releasetool` :)

**Pull request merged**
